-- Supabase has been removed from this project.
-- The SQLite schema is defined and auto-applied in server/db.js on startup.
--
-- Tables:
--   users       (id, email, password, role, first_name, last_name, created_at)
--   submissions (id, patient_id, first_name, last_name, age, gender,
--                body_areas, selected_symptoms, duration, severity,
--                additional_info, triage_level, status, created_at)
--   gp_actions  (id, submission_id, gp_id, action_type, notes, created_at)
--
-- The SQLite database file is created at server/digidoc.db on first run.
